name: Document Generation Service

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # TODO we will generate it from ODS
      image: s2obcn/jdk-11_openj9-wkhtmltopdf-ubi:main
      env:
        WKHTML_TO_PDF_WITH_DOCKER: false
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with Gradle
        run: ./gradlew clean test --stacktrace --no-daemon

      - name: TestReport
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: JUnit Report
          path: build/reports/**/**
