name: Document Generation Service

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: download and install wkhtml 
      run: | 
        sudo apt install curl
        sudo curl -kLO https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb --output wkhtmltox.deb
        sudo dpkg -i wkhtmltox.deb 
    - name: Build with Gradle
      run: ./gradlew clean check --stacktrace --no-daemon
      env:
        NO_NEXUS: true
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: TestReport
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
          name: JUnit Report
          path: build/reports/**/**
    - name: Push docker image
      if: success() && github.repository == 'opendevstack/ods-document-generation-svc' && github.event_name == 'push'
      shell: bash
      env:
        DOCKER_USER: ${{ secrets.DockerHubUser }}
        DOCKER_PASS: ${{ secrets.DockerHubPass }}
      run: ./.github/workflows/push-image.sh ${{ github.ref }} "$DOCKER_USER" "$DOCKER_PASS"

